/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PressRouteImport } from './routes/press'
import { Route as PersonalCareRouteImport } from './routes/personal-care'
import { Route as MyJourneyRouteImport } from './routes/my-journey'
import { Route as InnovationRouteImport } from './routes/innovation'
import { Route as ContemporaryRouteImport } from './routes/contemporary'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollaborationsRouteImport } from './routes/collaborations'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalCareRoute = PersonalCareRouteImport.update({
  id: '/personal-care',
  path: '/personal-care',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJourneyRoute = MyJourneyRouteImport.update({
  id: '/my-journey',
  path: '/my-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationRoute = InnovationRouteImport.update({
  id: '/innovation',
  path: '/innovation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContemporaryRoute = ContemporaryRouteImport.update({
  id: '/contemporary',
  path: '/contemporary',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsRoute = CollaborationsRouteImport.update({
  id: '/collaborations',
  path: '/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collaborations': typeof CollaborationsRoute
  '/contact': typeof ContactRoute
  '/contemporary': typeof ContemporaryRoute
  '/innovation': typeof InnovationRoute
  '/my-journey': typeof MyJourneyRoute
  '/personal-care': typeof PersonalCareRoute
  '/press': typeof PressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collaborations': typeof CollaborationsRoute
  '/contact': typeof ContactRoute
  '/contemporary': typeof ContemporaryRoute
  '/innovation': typeof InnovationRoute
  '/my-journey': typeof MyJourneyRoute
  '/personal-care': typeof PersonalCareRoute
  '/press': typeof PressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collaborations': typeof CollaborationsRoute
  '/contact': typeof ContactRoute
  '/contemporary': typeof ContemporaryRoute
  '/innovation': typeof InnovationRoute
  '/my-journey': typeof MyJourneyRoute
  '/personal-care': typeof PersonalCareRoute
  '/press': typeof PressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$productId': typeof ProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/collaborations'
    | '/contact'
    | '/contemporary'
    | '/innovation'
    | '/my-journey'
    | '/personal-care'
    | '/press'
    | '/sitemap.xml'
    | '/product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/collaborations'
    | '/contact'
    | '/contemporary'
    | '/innovation'
    | '/my-journey'
    | '/personal-care'
    | '/press'
    | '/sitemap.xml'
    | '/product/$productId'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/collaborations'
    | '/contact'
    | '/contemporary'
    | '/innovation'
    | '/my-journey'
    | '/personal-care'
    | '/press'
    | '/sitemap.xml'
    | '/product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollaborationsRoute: typeof CollaborationsRoute
  ContactRoute: typeof ContactRoute
  ContemporaryRoute: typeof ContemporaryRoute
  InnovationRoute: typeof InnovationRoute
  MyJourneyRoute: typeof MyJourneyRoute
  PersonalCareRoute: typeof PersonalCareRoute
  PressRoute: typeof PressRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-care': {
      id: '/personal-care'
      path: '/personal-care'
      fullPath: '/personal-care'
      preLoaderRoute: typeof PersonalCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-journey': {
      id: '/my-journey'
      path: '/my-journey'
      fullPath: '/my-journey'
      preLoaderRoute: typeof MyJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation': {
      id: '/innovation'
      path: '/innovation'
      fullPath: '/innovation'
      preLoaderRoute: typeof InnovationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contemporary': {
      id: '/contemporary'
      path: '/contemporary'
      fullPath: '/contemporary'
      preLoaderRoute: typeof ContemporaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations': {
      id: '/collaborations'
      path: '/collaborations'
      fullPath: '/collaborations'
      preLoaderRoute: typeof CollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollaborationsRoute: CollaborationsRoute,
  ContactRoute: ContactRoute,
  ContemporaryRoute: ContemporaryRoute,
  InnovationRoute: InnovationRoute,
  MyJourneyRoute: MyJourneyRoute,
  PersonalCareRoute: PersonalCareRoute,
  PressRoute: PressRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
